apiVersion: v2
name: shlink
description: A Helm chart for Kubernetes
icon: https://shlink.io/favicon.svg
type: application
version: v1.0.1
appVersion: 3.6.0
dependencies:
  - name: mariadb
    version: "12.2.4"
    repository: "file://charts/mariadb-10.4.0.tgz"
