apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink.fullname" . }}
  labels:
    {{- include "shlink.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shlink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shlink.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "shlink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEFAULT_DOMAIN
              value: {{required "Short Domain Host required" .Values.env.DEFAULT_DOMAIN | quote }}
            - name: IS_HTTPS_ENABLED
              value: {{default "false" .Values.env.IS_HTTPS_ENABLED | quote }}
            - name:  DB_DRIVER
              value: "maria"
            - name:  DB_HOST
              value: shlink-mariadb
            - name:  DB_USER
              value: "shlink"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shlink-mariadb
                  key: mariadb-password
            {{- if .Values.env.DEFAULT_INVALID_SHORT_URL_REDIRECT }}
            - name: DEFAULT_INVALID_SHORT_URL_REDIRECT
              value: {{ .Values.env.DEFAULT_INVALID_SHORT_URL_REDIRECT }}
            {{- end }}
            {{- if .Values.env.DEFAULT_BASE_URL_REDIRECT }}
            - name: DEFAULT_BASE_URL_REDIRECT
              value: {{ .Values.env.DEFAULT_BASE_URL_REDIRECT }}
            {{- end }}
            - name: ANONYMIZE_REMOTE_ADDR
              value: {{ .Values.env.ANONYMIZE_REMOTE_ADDR | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /rest/v2/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
