{{- if .Values.ingress.enabled -}}
{{- $fullName := include "shlink.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "shlink.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.env.DEFAULT_DOMAIN }}
      secretName: {{ .Values.env.DEFAULT_DOMAIN }}-secret
  rules:
    - host: {{ .Values.env.DEFAULT_DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-service
                port:
                  number: {{ $svcPort }}
{{- end }}
